/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

sourceSets.main {
    java.srcDirs("src/")
}

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    //Parser
    maven { "https://kotlin.bintray.com/kotlinx" }
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    //Logger
    implementation("org.apache.logging.log4j")
    implementation("org.apache.logging.log4j")



    //Parser
    implementation("org.jetbrains.kotlinx:kotlinx-cli:0.3")
}

application {
    // Define the main class for the application.
    mainClassName = "AAAapp.AppKt"
}
