/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"
    //Flyway, migration tool
    id("org.flywaydb.flyway") version "7.3.0"
    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    //Parser
    maven { url = uri("https://kotlin.bintray.com/kotlinx") }
    //h2db
    maven { url = uri("https://mvnrepository.com/artifact/com.h2database/h2") }
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    //Logger
    implementation("org.apache.logging.log4j:log4j-api:2.7")
    implementation("org.apache.logging.log4j:log4j-core:2.7")

    //Parser
    implementation("org.jetbrains.kotlinx:kotlinx-cli:0.3")

    //h2db
    implementation("com.h2database:h2:1.3.148")

    //FlyWay
    implementation("org.flywaydb:flyway-core:7.3.0")
}

application {
    // Define the main class for the application.
    mainClassName = "AAAapp.AppKt"
}